package models;

public enum Area {
    CARGASVARIAS,
    COMBUSTIBLE,
    CONTABILIDADFINANZAS,
    DESARROLLO,
    FLOTA,
    GERENCIA,
    GESTIONYMEJORACONTINUA,
    LOGISTICA,
    MANTENIMIENTO,
    OPERACIONES,
    RECURSOSCRITICOS,
    RECURSOSHUMANOS,
    SSOMA
}
